export const SIMULATION_CONFIG = {
  macro: {
    rateMin: 0, rateMax: 8,
    inflationMin: 0, inflationMax: 7,
    unemploymentMin: 3, unemploymentMax: 12,
    gdpMin: -3.5, gdpMax: 4.5,
    noiseRateRange: 0.08,
    noiseInflationRange: 0.1,
    noiseUnemploymentRange: 0.08,
    noiseGdpRange: 0.15,
    noiseSentimentRange: 0.08,
    rateDriftFactor: 0.4,
    inflationDriftFactor: 0.5,
    unemploymentDriftFactor: 0.8,
    sentimentGdpFactor: 0.05,
    sentimentUnemploymentFactor: 0.02,
    sentimentRateFactor: 0.015,
    sentimentMin: -1, sentimentMax: 1,
  },
  phase: {
    expansionToSlowdown: 0.18,
    slowdownTransition: 0.22,
    gdpSlowdownThreshold: 1.2,
    recessionToRecovery: 0.35,
    recoveryToExpansion: 0.3,
  },
  stocks: {
    driftFairValueFactor: 0.25,
    driftSentimentFactor: 0.05,
    driftMacroFactor: 0.001,
    maxDriftChange: 0.2,
    priceMin: 4, priceMax: 320,
    growthMin: -0.08, growthMax: 0.18,
    growthMacroFactor: 0.002,
    marginMin: 0.08, marginMax: 0.45,
    debtMin: 120, debtMax: 2600,
    riskMin: 0.12, riskMax: 0.6,
    revenueMin: 800, revenueMax: 9000,
    cashMin: 200, cashMax: 2200,
    cashGrowthFactor: 0.4,
    capexMin: 120, capexMax: 1200,
    capexGrowthFactor: 0.3,
  },
  bonds: {
    durationImpactFactor: 0.012,
    maxPriceChange: 0.08,
    priceMin: 70, priceMax: 130,
    yieldRateFactor: 0.25,
    yieldMin: 0, yieldMax: 10,
  },
  etfs: {
    meanReversionFactor: 0.3,
    maxPriceChange: 0.12,
    priceMin: 18, priceMax: 220,
  },
  commodities: {
    anchorConvergenceFactor: 0.2,
    overheatPenaltyFactor: 0.1,
    maxOverheat: 0.5,
    priceFloorAbsolute: 5,
  },
  portfolio: {
    cashYieldDivisor: 5200,   // 52 settimane * 100 (rate in %)
    maxLeverageRatio: 0.5,
    maxDebtAbsolute: 100_000,
  },
  simulation: {
    netWorthHistoryWeeks: 24,
    maxNewsFeedItems: 20,
    twoEventsThreshold: 0.72,
  },
} as const;
